import type { NextPage } from "next";
import Head from "next/head";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { useWallet } from "@solana/wallet-adapter-react";

const Home: NextPage = () => {
    const { publicKey } = useWallet();

    return (
        <div className="App">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <WalletMultiButton />
                <h1
                    style={{
                        textAlign: "center",
                        marginTop: "1rem",
                        color: "#fff",
                    }}
                >
                    {publicKey?.toBase58()}
                </h1>
            </main>
        </div>
    );
};

export default Home;
